name: Integration tests

env:
  ignore-changed-paths: ["**.md", "**LICENSE", "**.gitignore", "**.clang-format", "library.json"]

on:
  push:
    paths-ignore: ${{ env.ignore-changed-paths }}
  pull_request:
    paths-ignore: ${{ env.ignore-changed-paths }}

jobs:
  install-tools:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install libhamlib-utils
      run: |
        sudo apt install -y libhamlib-utils socat
    - name: Run integration tests
      run: |
        cd test
        platformio run -e native -t integrationci
