name: Integration tests
on: [push, pull_request]

jobs:
  install-tools:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Install libhamlib-utils
      run: |
        sudo apt install -y libhamlib-utils socat
    - name: Run integration tests
      run: |
        cd test
        platformio run -e native -t integration
