name: Integration tests - Hamlib from source

on: [workflow_dispatch]

jobs:
  install-tools:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install libhamlib-utils from source
      run: |
        sudo apt install -y git make build-essential autoconf automake libtool shtool pkg-config libusb-1.0-0-dev
        cd
        git clone https://github.com/Hamlib/Hamlib.git ./hamlib
        cd hamlib
        ./bootstrap
        ./configure
        make
        sudo make install
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install socat
      run: |
        sudo apt install -y socat
    - name: Run integration tests
      run: |
        cd test
        platformio run -e native -t integrationci
