name: Integration tests - Hamlib from source

on: [workflow_dispatch]

jobs:
  install-tools:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Restore Hamlib Cache
      uses: actions/cache@v3
      id: hamlib-cache
      with:
        path: ~/hamlib-src
        key: ${{ runner.os }}-hamlib
    - name: Crate Hamlib Cache
      if: steps.hamlib-cache.outputs.cache-hit != 'true'
      run: |
        git clone --depth 1 --branch 4.4 https://github.com/Hamlib/Hamlib.git ~/hamlib-src
    - name: build and install Hamlib I
      run: |
        sudo apt install -y make build-essential autoconf automake libtool shtool pkg-config libusb-1.0-0-dev
        cd ~/hamlib-src
        ./bootstrap
        ./configure
      continue-on-error: true
    - name: build and install Hamlib II
      run: |
        cd ~/hamlib-src
        make
        sudo make install
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install socat
      run: |
        sudo apt install -y socat
    - name: Run integration tests
      run: |
        cd test
        platformio run -e native -t integrationci
