on: [push, pull_request]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run tests on the native platform
      run: |
        cd test
        platformio test -e native
    - name: install libhamlib-utils
      run: |
        sudo apt install -y libhamlib-utils
    - name: Run integration tests on native platform
      run: |
        cd test
        platformio run -e native_integration_test
