name: run integration tests
on: [push, pull_request]

jobs:
  install:
    call-install-workflow:
      uses: ./.github/workflows/install.yaml
  integration-tests:
    steps:
    - name: install libhamlib-utils
      run: |
        sudo apt install -y libhamlib-utils socat
    - name: Run integration tests on native platform
      run: |
        cd test
        platformio run -e native -t integration
