name: Unit tests

on:
  push:
    paths-ignore:
      - "**.md"
      - "**LICENSE"
      - "**.gitignore"
      - "**.clang-format"
      - "library.json"
      - "**manual-run.yaml"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**LICENSE"
      - "**.gitignore"
      - "**.clang-format"
      - "library.json"
      - "**manual-run.yaml"

jobs:
  install-tools:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Unit tests
      run: |
        cd test
        platformio test -e native
