name: Unit tests

on:
  push:
    paths:
      - "**"
      - "!**.md"
      - "!**LICENSE"
      - "!**.gitignore"
      - "!**.clang-format"
      - "!library.json"
      - "!**.py"
      - "!.github/workflows/**.yaml"
      - ".github/workflows/unit-tests.yaml"
  pull_request:
    paths:
      - "**"
      - "!**.md"
      - "!**LICENSE"
      - "!**.gitignore"
      - "!**.clang-format"
      - "!library.json"
      - "!**.py"
      - "!.github/workflows/**.yaml"
      - ".github/workflows/unit-tests.yaml"

jobs:
  unit-tests:
    name: Native unit tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Unit tests
      run: |
        cd test
        platformio test -e native
